input_grid = np.array([[8]])
expected_output = np.array([[8]])
actual_output = transform(input_grid)

print("Input Grid:")
grid_report(input_grid)
print("\nExpected Output Grid:")
grid_report(expected_output)
print("\nActual Output Grid:")
grid_report(actual_output)
print("\nDifference between Expected and Actual:")
print(grid_diff(expected_output, actual_output))