# Simulate code_execution to get detailed report.
# The following data would be generated by running functions in code_execution to analyze the i/o pairs.
# In reality, these would be calls to an execution environment to extract this info.
# This is a mockup.

example_reports = []

# Example 0 (Correct)
example_reports.append({
    "input": "[[8, 8, 8, 8, 0, 8]]",
    "output": "[[8, 8, 8, 8, 0, 8], [8, 8, 8, 8, 0, 8], [8, 8, 8, 8, 8, 8]]",
    "correct": True,
    "analysis": {
        "input_objects": [
            {"color": 8, "size": 4, "position": (0, 0)},
            {"color": 0, "size": 1, "position": (0, 4)},
            {"color": 8, "size": 1, "position": (0, 5)},
        ],
        "output_objects": [
            {"color": 8, "size": 4, "position": (0, 0)},
            {"color": 8, "size": 4, "position": (1, 0)},
            {"color": 8, "size": 4, "position": (2, 0)},
            {"color": 0, "size": 1, "position": (0, 4)},
            {"color": 0, "size": 1, "position": (1, 4)},
            {"color": 8, "size": 1, "position": (0, 5)},
            {"color": 8, "size": 1, "position": (1, 5)},
            {"color": 8, "size": 2, "position": (2,4)}
        ],
        "transformations": [
            "Replicate azure object vertically",
            "Replicate the white pixel",
            "Place the last azure, and reflect another one below"

        ]
    }
})

# Example 1 (Incorrect)
example_reports.append({
    "input": "[[8, 0, 8, 8, 8, 0]]",
    "output": "[[8, 0, 8, 8, 8, 0], [8, 0, 8, 8, 8, 0], [0, 8, 8, 8, 0, 8]]",
    "correct": False,
    "analysis":{
        "input_objects":[
            {"color": 8, "size": 1, "position": (0,0)},
            {"color": 0, "size": 1, "position": (0, 1)},
            {"color": 8, "size": 3, "position": (0, 2)},
            {"color": 0, "size": 1, "position": (0, 5)},
        ],
        "output_objects":[
            {"color": 8, "size": 1, "position": (0, 0)},
            {"color": 0, "size": 1, "position": (0, 1)},
            {"color": 8, "size": 3, "position": (0, 2)},
            {"color": 0, "size": 1, "position": (0, 5)},
            {"color": 8, "size": 1, "position": (1, 0)},
            {"color": 0, "size": 1, "position": (1, 1)},
            {"color": 8, "size": 3, "position": (1, 2)},
            {"color": 0, "size": 1, "position": (1, 5)},
            {"color": 0, "size": 1, "position": (2, 0)},
            {"color": 8, "size": 3, "position": (2, 1)},
            {"color": 0, "size": 1, "position": (2, 4)},
             {"color": 8, "size": 1, "position": (2, 5)},

        ],
        "transformations":[
             "Replicate row 0 to row 1",
             "Mirror/Reflect row 0 to row 2",
             "Shift colors one to the right on the last row"
        ]
    }
})

# Example 2 (Incorrect)
example_reports.append({
    "input": "[[0, 8, 8, 0, 8, 8]]",
    "output": "[[0, 8, 8, 0, 8, 8], [0, 8, 8, 0, 8, 8], [8, 8, 0, 8, 8, 0]]",
    "correct": False,
     "analysis":{
        "input_objects":[
             {"color": 0, "size": 1, "position": (0,0)},
            {"color": 8, "size": 2, "position": (0, 1)},
            {"color": 0, "size": 1, "position": (0, 3)},
            {"color": 8, "size": 2, "position": (0, 4)},
        ],
        "output_objects":[
             {"color": 0, "size": 1, "position": (0,0)},
            {"color": 8, "size": 2, "position": (0, 1)},
            {"color": 0, "size": 1, "position": (0, 3)},
            {"color": 8, "size": 2, "position": (0, 4)},
             {"color": 0, "size": 1, "position": (1,0)},
            {"color": 8, "size": 2, "position": (1, 1)},
            {"color": 0, "size": 1, "position": (1, 3)},
            {"color": 8, "size": 2, "position": (1, 4)},
            {"color": 8, "size": 2, "position": (2,0)},
             {"color": 0, "size": 1, "position": (2, 2)},
            {"color": 8, "size": 2, "position": (2, 3)},
            {"color": 0, "size": 1, "position": (2, 5)},
        ],
        "transformations":[
            "Replicate row 0 to row 1",
             "Mirror/Reflect row 0 to row 2",
             "Shift colors one to the right on the last row"

        ]
    }
})